config/routes.rb
Rails.application.routes.draw do

  # resources :todos
  # devise_for :users
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "home#api_list"

  scope module: 'api' do
    # From here Api routes for Mobile App starts
    namespace :v1 do

      resources :todos do
        put 'is_completed', on: :member
      end

      resources :sessions, only: [], path: '' do
        collection do
          post 'login', to: 'sessions#create' # /v1/login
          post 'signup'                       # /v1/signup
        end
      end
    end

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_one :user

  acts_as_api

  api_accessible :todo_list do |t|
    t.add :id
    t.add :data
    t.add :due_date
    t.add :priority
    t.add :is_completed
    t.add :user_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos

  acts_as_api

  api_accessible :user do |t|
    t.add :id
    t.add :email
  end

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController

  private

  def render_data data, message
		render json: { success: true, message: message, data: data }, status: 200
	end

	def error_data message
		render json: { success: false, message: message, data: {} }, status: 404
	end

	def error_valid_data message
		render json: { success: false, message: message, data: {} }, status: 400
	end

	protected
	def login_required
		token = params[:access_token]
    token ||= request.headers["Access-Token"]
    decode_token = JsonWebToken.decode(token)

    error_valid_data(decode_token[:error]) and return if decode_token[:error].present?
    error_valid_data(decode_token[:error]) and return if decode_token.blank?

    @current_user = decode_token["user_id"].present? ? decode_token["user_id"] : nil
  end
end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Api::V1::BaseController
	before_action :check_null_password, :only => :create

	# POST /v1/login
	def create
		if @user && @user.valid_password?(params[:password])
			auth_token = JsonWebToken.encode({user_id: @user.id})
			render_data( { auth_token: auth_token, users: @user.as_api_response(:user) }, 'Login success..!!!' )
		else
			error_data( "Login errors...!!!" )
		end
	end

	# POST /v1/signup
	def signup
		user = User.new(user_params)

		if user.save!
			#user.refreshed_token
			auth_token = JsonWebToken.encode({user_id: user.id})
			render_data( { auth_token: auth_token, users: user.as_api_response(:user) }, 'Signup success..!!!!' )
		end
	rescue ActiveModel::StrictValidationFailed => e
		error_valid_data(e)
	rescue ActiveRecord::RecordNotUnique => e
		error_valid_data(e)
	rescue StandardError => e
		err = user.errors.full_messages.try(:first).present? ? user.errors.full_messages.try(:first) : e
		error_valid_data(err)
	end


	private
	def user_params
		params.permit(:email, :password, :password_confirmation)
	end

	def check_null_password
		@user = User.find_by(email: params[:email].downcase)

		if @user.present?
			# error_valid_data(I18n.t('user.wrong_signin_way'))	if @user.password_digest.nil?
		end
	end

end

app/controllers/api/v1/todos_controller.rb
class Api::V1::TodosController < Api::V1::BaseController

	before_action :login_required
	before_action :set_todo, only: [:show, :edit, :update, :destroy, :is_completed]

	# GET /admin/v1/todos
	def index
		limit = params[:limit].to_i == -1 ? 100 : params[:limit]

		sort_by = params[:sort_by]

		sort_direction = params[:sort_direction]

		@todos_total = Todo.where(user_id: @current_user).order("#{sort_by} #{sort_direction}")

		@todos = @todos_total.paginate(:page => params[:page], :per_page => limit).offset(params[:offset])

		render_data({total: @todos_total.count, result_total: @todos.count, todos: @todos.as_api_response(:todo_list)},'todos list..!!!') if @todos
	end

	def create
    @todo = Todo.new(todo_params)
      if @todo.save
				@todo.update(user_id: @current_user)
				render_data({ todo: @todo.as_api_response(:todo_list) }, 'Create successfully..!!!' )
      else
				 error_data( 'Errors while create new todo...!!!!' )
      end
  end

	# DELETE
	def destroy
		render_data({ todo: {} }, 'todo deleted...!!!') if @todo.destroy!
	end

	# GET
	def show
		render_data({ todos: @todo.as_api_response(:todo_list) }, 'Todo detail..!!!!')
	end


	# PATCH/PUT /todos/1
	# PATCH/PUT /todos/1.json
	def update
		if @todo.update(todo_params)
			render_data({ todos: @todo.as_api_response(:todo_list) }, "Todo was successfully updated.")
		else
			error_data( 'Errors while create new todo...!!!!' )
		end
	end

	# PATCH/PUT /todos/1
	# PATCH/PUT /todos/1.json
	def is_completed
		if @todo.update(is_completed: !@todo.is_completed)
			render_data({ todos: @todo.as_api_response(:todo_list) }, "Todo was successfully updated.")
		else
			error_data( 'Errors while create new todo...!!!!' )
		end
	end

	private

	# Use callbacks to share common setup or constraints between actions.
	def set_todo
		@todo = Todo.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def todo_params
		params.permit(:data, :due_date, :priority, :is_completed, :user)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API

	# Call this to make acts_as_api work
	include ActsAsApi::Rendering

	before_action :set_locale
  before_action :set_headers

  ##------------------------ Exception Handling --------------------------- ##

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  rescue_from ActiveRecord::RecordInvalid do |e|
    render json: { success: false, message: e, data: {} }, status: 404
  end

  rescue_from I18n::InvalidLocale, :with => :locale_not_valid

  rescue_from ActiveModel::StrictValidationFailed do |e|
    render json: { success: false, message: e, data: {} }, status: 404
  end

  # Handle required missing params error with custom method
  # rescue_from CustomErrors::MissingParams do |e| render_missing_params_error(names: e.names) end

  ##---------------------------------- end ---------------------------------##


  private
  def record_not_found
    render json: { success: false, message: I18n.t('record_not_found'), data: {} }, status: 404
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def locale_not_valid
  	render json: { success: false, message: "locale not valid only en or ar is allowed.", data: {} }, status: 404
  end

  def set_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS, PATCH'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end

  # This method will check required_params list to be included in params
  def check_required_params(params, required_params)
    missing_params = []
    required_params.each { |p| missing_params << p if params[p].blank? }
    raise CustomErrors::MissingParams.new(missing_params) if missing_params.any?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def api_list
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/api_list.html.erb
<h1>Home#api_list</h1>
<p>Find me in app/views/home/api_list.html.erb</p>


<p><%= link_to('Logout', destroy_user_session_path, method: :delete) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_area :data, id: :todo_data %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_select :due_date, id: :todo_due_date %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority, id: :todo_priority %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Due date</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.data %></td>
        <td><%= todo.due_date %></td>
        <td><%= todo.priority %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @todo.data %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todo.due_date %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @todo.priority %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>